version: '2'
services:
  db:
    image: mysql:8.0.34
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ChangeMe
      MYSQL_DATABASE: mojito
      MYSQL_USER: mojito
      MYSQL_PASSWORD: ChangeMe
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
    ports:
      - "3307:3306"
  webapp:
    depends_on:
      - db
    image: mojito:latest
    links:
      - db
    ports:
      - "8080:8080"
    restart: always
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.flyway.enabled": "true",
      "spring.jpa.defer-datasource-initialization": "false",
      "l10n.flyway.clean": "true",
      "spring.flyway.cleanDisabled" : "false",
      "spring.flyway.clean-disabled": "false",
      "spring.jpa.database-platform" : "org.hibernate.dialect.MySQLDialect",
      "spring.jpa.hibernate.ddl-auto" : "none",
      "spring.datasource.url" : "jdbc:mysql://db:3306/mojito?characterEncoding=UTF-8&useUnicode=true",
      "spring.datasource.username" : "mojito",
      "spring.datasource.password" : "ChangeMe",
      "spring.datasource.driverClassName" : "com.mysql.cj.jdbc.Driver"
      }'
