version: '2'
services:
  compile:
#    image: aurambaj/mojito-dev
    build:
      dockerfile: dev/Dockerfile
      context: .
    working_dir: /mnt/mojito
    volumes:
      - ..:/mnt/mojito
      - ~/.m2:/root/.m2
    command: mvn clean install -DskipTests
    #command:  mvn test -P'!frontend' -Dtest=MultiBranchStateServiceTest -DfailIfNoTests=false

