DROP TABLE IF EXISTS SPRING_SESSION_V2_ATTRIBUTES;
DROP TABLE IF EXISTS SPRING_SESSION_V2;

CREATE TABLE SPRING_SESSION_V2 (
                                   PRIMARY_ID CHAR(36) NOT NULL,
                                   SESSION_ID CHAR(36) NOT NULL,
                                   CREATION_TIME BIGINT NOT NULL,
                                   LAST_ACCESS_TIME BIGINT NOT NULL,
                                   MAX_INACTIVE_INTERVAL INT NOT NULL,
                                   EXPIRY_TIME BIGINT NOT NULL,
                                   PRINCIPAL_NAME VARCHAR(100),
                                   CONSTRAINT SPRING_SESSION_V2_PK PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX SPRING_SESSION_V2_IX1 ON SPRING_SESSION_V2 (SESSION_ID);
CREATE INDEX SPRING_SESSION_V2_IX2 ON SPRING_SESSION_V2 (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_V2_IX3 ON SPRING_SESSION_V2 (PRINCIPAL_NAME);

CREATE TABLE SPRING_SESSION_V2_ATTRIBUTES (
                                              SESSION_PRIMARY_ID CHAR(36) NOT NULL,
                                              ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
                                              ATTRIBUTE_BYTES LONGVARBINARY NOT NULL,
                                              CONSTRAINT SPRING_SESSION_V2_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
                                              CONSTRAINT SPRING_SESSION_V2_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION_V2(PRIMARY_ID) ON DELETE CASCADE
);

ALTER TABLE rewrite_rules
    ADD COLUMN repository_id_scope BIGINT GENERATED ALWAYS AS (COALESCE(repository_id, 0));

ALTER TABLE rewrite_rules
    ADD COLUMN active_rewrite_from VARCHAR(512)
        GENERATED ALWAYS AS (CASE WHEN enabled THEN rewrite_from END);

CREATE UNIQUE INDEX I__REWRITE_RULES__REPO_ID_SCOPE__LOCALE_ID__ACTIVE_REWRITE_FROM
    ON rewrite_rules (repository_id_scope, locale_id, active_rewrite_from);