name: Run tests - Ubuntu + Java 11

on:
  [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11.0.19+7
      - name: Spotless check
        run: mvn spotless:check
      - name: Maven install, test skipped
        run: mvn install -DskipTests
      - name: Maven test
        run: mvn test